/**
 * Parity of js/drift-control-sandbox.js with its Python reference (#4533).
 * Golden vectors: tests/fixtures/widgets/drift-control-sandbox.parity.json,
 * generated by `python -m scripts.generate_widget_parity` (ADR 0002 section 6).
 */
const fs = require('fs');
const path = require('path');
const DCS = require('../js/drift-control-sandbox.js');

const fixture = JSON.parse(fs.readFileSync(
  path.join(__dirname, 'fixtures/widgets/drift-control-sandbox.parity.json'), 'utf8'));

/** ADR 0002 rule: |actual - expected| <= abs + rel * |expected|, element by element. */
function expectClose(actual, expected, tolerance, label) {
  if (Array.isArray(expected)) {
    expect(actual).toHaveLength(expected.length);
    expected.forEach((value, i) => expectClose(actual[i], value, tolerance, `${label}[${i}]`));
    return;
  }
  const bound = tolerance.abs + tolerance.rel * Math.abs(expected);
  const error = Math.abs(actual - expected);
  if (!(error <= bound)) throw new Error(`${label}: |${actual} - ${expected}| = ${error} > ${bound}`);
}

describe('drift-control sandbox parity fixture', () => {
  test('declares the v1 schema and cites the Python source', () => {
    expect(fixture.schema).toBe('affinedrift/widget-parity/v1');
    expect(fixture.widget).toBe('drift-control-sandbox');
    expect(fixture.source).toBe('src/affine_control/double_pendulum_affine.py::simulate');
  });

  const splitCases = fixture.cases.filter(c => c.id.startsWith('split-'));
  const presetCases = fixture.cases.filter(c => c.id.startsWith('preset-'));

  test.each(splitCases.map(c => [c.id, c]))('same-state split %s', (_id, c) => {
    const tolerance = c.tolerance || fixture.tolerance;
    const p = DCS.makeParams(c.inputs.params);
    const torque = DCS.generalizedTorque(c.inputs.shoulder, c.inputs.wrist);
    const [drift, input] = DCS.affineSplit(c.inputs.q, c.inputs.qd, torque, p);
    const [tipDrift, tipInput] = DCS.tipAccelerationSplit(c.inputs.q, c.inputs.qd, drift, input, p);
    expectClose(torque, c.expected.torque, tolerance, 'torque');
    expectClose(drift, c.expected.drift_qdd, tolerance, 'drift_qdd');
    expectClose(input, c.expected.input_qdd, tolerance, 'input_qdd');
    expectClose(tipDrift, c.expected.tip_drift, tolerance, 'tip_drift');
    expectClose(tipInput, c.expected.tip_input, tolerance, 'tip_input');
  });

  test.each(presetCases.map(c => [c.id, c]))('integrated trajectory %s', (_id, c) => {
    const tolerance = c.tolerance || fixture.tolerance;
    const i = c.inputs;
    const samples = DCS.simulate(
      DCS.makeParams(i.params), i.q0, i.qd0, DCS.generalizedTorque(i.shoulder, i.wrist),
      i.horizon, i.steps);
    const kept = samples.filter((_, index) => index % i.sample_every === 0);
    expectClose(kept.map(s => s.t), c.expected.t, tolerance, 't');
    expectClose(kept.map(s => s.q), c.expected.q, tolerance, 'q');
    expectClose(kept.map(s => s.qd), c.expected.qd, tolerance, 'qd');
    expectClose(kept.map(s => s.driftQdd), c.expected.drift_qdd, tolerance, 'drift_qdd');
    expectClose(kept.map(s => s.inputQdd), c.expected.input_qdd, tolerance, 'input_qdd');
  });

  test('widget presets and defaults are the fixture scenarios', () => {
    expect(presetCases.length).toBe(Object.keys(DCS.PRESETS).length);
    for (const c of presetCases) {
      const name = c.id.replace(/^preset-/, '');
      expect(DCS.PRESETS[name]).toEqual({shoulder: c.inputs.shoulder, wrist: c.inputs.wrist});
      expect(DCS.DEFAULTS.params).toEqual(c.inputs.params);
      expect(DCS.DEFAULTS.q0).toEqual(c.inputs.q0);
      expect(DCS.DEFAULTS.qd0).toEqual(c.inputs.qd0);
      expect(DCS.DEFAULTS.horizon).toBe(c.inputs.horizon);
      expect(DCS.DEFAULTS.steps).toBe(c.inputs.steps);
    }
  });
});

describe('drift-control sandbox contracts', () => {
  test('rejects nonphysical parameters', () => {
    expect(() => DCS.makeParams({m1: 0, m2: 1, l1: 1, l2: 1})).toThrow(/m1/);
    expect(() => DCS.makeParams({m1: 1, m2: 1, l1: NaN, l2: 1})).toThrow(/l1/);
  });

  test('rejects a bad horizon or step count', () => {
    const p = DCS.makeParams(DCS.DEFAULTS.params);
    expect(() => DCS.simulate(p, [0, 0], [0, 0], [0, 0], 0, 10)).toThrow(/horizon/);
    expect(() => DCS.simulate(p, [0, 0], [0, 0], [0, 0], 1, 0)).toThrow(/steps/);
  });

  test('drift ignores the input and the input term is linear', () => {
    const p = DCS.makeParams(DCS.DEFAULTS.params);
    const [driftA, inputA] = DCS.affineSplit([2.3, 3.6], [-1.5, 2], [10, -2], p);
    const [driftB, inputB] = DCS.affineSplit([2.3, 3.6], [-1.5, 2], [-40, 5], p);
    expect(driftA).toEqual(driftB);
    const [, inputSum] = DCS.affineSplit([2.3, 3.6], [-1.5, 2], [-30, 3], p);
    expectClose(inputSum, [inputA[0] + inputB[0], inputA[1] + inputB[1]], {abs: 1e-12, rel: 1e-12}, 'linear');
  });

  test('christoffel Coriolis agrees with the closed form', () => {
    const p = DCS.makeParams(DCS.DEFAULTS.params);
    const numeric = DCS.christoffelCoriolis(q => DCS.massMatrix(q, p), [0.7, -0.4], [1.2, -2.1]);
    expectClose(numeric, DCS.coriolis([0.7, -0.4], [1.2, -2.1], p), {abs: 1e-8, rel: 1e-8}, 'C');
  });
});
