"""Pure deterministic report helpers for the scientific claim-audit inventory."""

from __future__ import annotations

from collections import Counter
from pathlib import Path
from typing import cast

BLOCKING_PRIORITIES = frozenset({"p0", "p1"})
BLOCKED_DISPOSITION = "publication_blocked"
MANIFEST_CONTRACT = "affinedrift/public-site-manifest/v1"
REVIEW_DIMENSIONS = frozenset({"evidence", "uncertainty", "falsifiers", "audience_framing"})


def publication_blocker_ids(records: list[dict[str, object]]) -> list[str]:
    """Return sorted P0/P1 finding IDs that explicitly block publication."""
    return sorted(
        str(finding["finding_id"])
        for record in records
        for finding in cast(list[dict[str, object]], record["findings"])
        if finding["priority"] in BLOCKING_PRIORITIES
        and finding["disposition"] == BLOCKED_DISPOSITION
    )


def build_joined_report(
    records: list[dict[str, object]],
    claims: dict[str, dict[str, object]],
    critiques: dict[str, dict[str, object]],
) -> dict[str, object]:
    """Join route audit state to the two authoritative ID registries."""
    counts = Counter(str(record["status"]) for record in records)
    routes: list[dict[str, object]] = []
    for record in records:
        routes.append(
            {
                "audit_id": record["audit_id"],
                "route": record["route"],
                "status": record["status"],
                "claims": [
                    {"claim_id": claim_id, "title": claims[claim_id].get("title", "")}
                    for claim_id in cast(list[str], record["claim_ids"])
                ],
                "critiques": [
                    {
                        "critique_id": critique_id,
                        "disposition": critiques[critique_id].get("disposition", "unknown"),
                        "severity": critiques[critique_id].get("severity", "unknown"),
                    }
                    for critique_id in cast(list[str], record["critique_ids"])
                ],
                "findings": record["findings"],
            }
        )
    return {
        "counts": {key: counts.get(key, 0) for key in ("deferred", "exempt", "reviewed")},
        "inventory_schema_version": "1.0.0",
        "route_count": len(records),
        "routes": routes,
        "schema_version": "1.0.0",
    }


def render_markdown(report: dict[str, object]) -> str:
    """Render the joined inventory report as stable Markdown."""
    counts = report["counts"]
    routes = report.get("routes")
    if not isinstance(counts, dict) or not isinstance(routes, list):
        raise ValueError("Generated report is invalid")
    lines = [
        "# Scientific Claim-Audit Inventory",
        "",
        "<!-- DO NOT EDIT. Generated by scripts/generate_claim_audit_inventory.py. -->",
        "",
        "This report records route-level audit state. Claim text and critique adjudication remain authoritative in the #4019 claim registry and #4020 critique ledger.",
        "",
        f"- Reviewed: {counts.get('reviewed', 0)}",
        f"- Deferred: {counts.get('deferred', 0)}",
        f"- Exempt: {counts.get('exempt', 0)}",
        "",
        "| Audit ID | Route | Status | Claim IDs | Critique IDs | Findings |",
        "|---|---|---|---|---|---:|",
    ]
    for route in routes:
        if not isinstance(route, dict):
            raise ValueError("Generated route report is invalid")
        claim_ids = ", ".join(f"`{item['claim_id']}`" for item in route["claims"])
        critique_ids = ", ".join(f"`{item['critique_id']}`" for item in route["critiques"])
        lines.append(
            f"| `{route['audit_id']}` | `{route['route']}` | {str(route['status']).title()} "
            f"| {claim_ids or 'None'} | {critique_ids or 'None'} | {len(route['findings'])} |"
        )
    lines.append("")
    return "\n".join(lines)


def write_or_check(path: Path, expected: str, check: bool) -> None:
    """Write one generated report or verify its exact current contents."""
    if check:
        if not path.is_file() or path.read_text(encoding="utf-8") != expected:
            raise ValueError(f"Generated claim-audit report is stale: {path}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(expected, encoding="utf-8", newline="\n")
