#!/usr/bin/env python3
"""Convert bibliography.json to BibTeX format for Quarto inline citations.

Reads data/bibliography.json and writes references/affine-drift.bib.
Mapping:
  type=paper   -> @article
  type=book    -> @book
  type=article -> @misc (site article / preprint)
  type=software -> @misc

Closes issue #1529.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

from scripts.cli_output import write_stderr, write_stdout
from src.core.contracts import require

# ─── type mapping ─────────────────────────────────────────────────────────────

_TYPE_MAP: dict[str, str] = {
    "paper": "article",
    "book": "book",
    "article": "misc",
    "software": "misc",
}


# ─── helpers ──────────────────────────────────────────────────────────────────


def _sanitize_key(key: str) -> str:
    """Return a valid BibTeX citation key."""
    return re.sub(r"[^A-Za-z0-9_:-]", "", key)


def _format_authors(authors: list[str]) -> str:
    """Return BibTeX author string (names joined with ' and ')."""
    return " and ".join(str(a) for a in authors)


def _escape_bibtex(value: str) -> str:
    """Escape special characters for BibTeX values."""
    # Wrap in braces to protect LaTeX special chars
    return value.replace("\\", "\\\\").replace("{", "\\{").replace("}", "\\}")


def _entry_to_bibtex(entry: dict) -> str:  # type: ignore[type-arg]
    """Convert a single bibliography entry dict to a BibTeX entry string."""
    bib_type = _TYPE_MAP.get(entry.get("type", "paper"), "misc")
    key = _sanitize_key(entry.get("id", "unknown"))

    fields: list[str] = []

    title = entry.get("title", "")
    if title:
        fields.append(f"  title     = {{{_escape_bibtex(title)}}}")

    authors = entry.get("authors", [])
    if authors:
        fields.append(f"  author    = {{{_format_authors(authors)}}}")

    year = entry.get("year")
    if year:
        fields.append(f"  year      = {{{year}}}")

    venue = entry.get("venue", "")
    if venue:
        # Map venue to the appropriate BibTeX field
        if bib_type == "article":
            fields.append(f"  journal   = {{{_escape_bibtex(venue)}}}")
        elif bib_type == "book":
            fields.append(f"  publisher = {{{_escape_bibtex(venue)}}}")
        else:
            fields.append(f"  howpublished = {{{_escape_bibtex(venue)}}}")

    doi = entry.get("doi", "")
    if doi:
        fields.append(f"  doi       = {{{doi}}}")

    url = entry.get("url", "")
    if url and not doi:
        fields.append(f"  url       = {{{url}}}")

    description = entry.get("description", "")
    if description:
        fields.append(f"  note      = {{{_escape_bibtex(description[:200])}}}")

    body = ",\n".join(fields)
    return f"@{bib_type}{{{key},\n{body}\n}}"


# ─── main ─────────────────────────────────────────────────────────────────────


def main(repo_root: Path | None = None) -> int:
    """Convert bibliography.json to references/affine-drift.bib."""
    repo_root = repo_root or Path(__file__).resolve().parent.parent
    bib_json = repo_root / "data" / "bibliography.json"
    out_dir = repo_root / "references"
    out_path = out_dir / "affine-drift.bib"

    require(bib_json.exists(), f"bibliography.json not found: {bib_json}")

    entries = json.loads(bib_json.read_text(encoding="utf-8"))
    if not isinstance(entries, list):
        write_stderr(f"ERROR: bibliography.json must be a list, got {type(entries).__name__}")
        return 1

    out_dir.mkdir(exist_ok=True)

    lines = [
        "% AffineDrift Master Bibliography — auto-generated by scripts/convert_bibliography_to_bib.py",
        "% Do not edit manually. Edit data/bibliography.json and re-run the script.",
        "% Issue #1529: wire Quarto bibliography into article QMD frontmatter.",
        "",
    ]
    for entry in entries:
        lines.append(_entry_to_bibtex(entry))
        lines.append("")

    out_path.write_text("\n".join(lines), encoding="utf-8")
    write_stdout(f"Wrote {len(entries)} entries to {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
