#!/usr/bin/env python3
"""Generate or verify the governed E1--E8 research-readiness catalog."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.affine_control.research_readiness import (  # noqa: E402  # reason: direct CLI bootstrap
    build_public_summary,
    validate_library,
)
from src.affine_control.research_readiness.fixtures import (  # noqa: E402  # reason: direct CLI bootstrap
    build_manufactured_library,
    concept_template,
    manufactured_dictionary,
    manufactured_dry_runs,
)

LIBRARY = ROOT / "data/research_protocols/library.json"
DICTIONARY = ROOT / "data/research_protocols/data_dictionary.json"
DRY_RUNS = ROOT / "data/research_protocols/manufactured_dry_runs.json"
SUMMARY = ROOT / "data/research_protocols/public_summary.json"
TEMPLATE = ROOT / "data/research_protocols/protocol-template.json"
PARTIAL = ROOT / "_includes/generated/research-readiness-library.qmd"
SCHEMA = ROOT / "schemas/research-protocol-readiness-v1.schema.json"
CLAIMS = ROOT / "data/trust/claim_registry.json"
CRITIQUES = ROOT / "data/trust/claim_critique_ledger.json"


class StaleReadinessOutputError(ValueError):
    """Raised when a generated readiness artifact is absent or stale."""


def _json(value: object) -> str:
    return json.dumps(value, indent=2, ensure_ascii=False, sort_keys=True) + "\n"


def _partial(summary: dict[str, object]) -> str:
    lines = [
        "<!-- Generated by scripts/generate_research_readiness_library.py. -->",
        "",
        "| Program | Readiness | Evidence Origin | Next Blocking Gate |",
        "|---|---|---|---|",
    ]
    protocols = summary["protocols"]
    if not isinstance(protocols, list):
        raise StaleReadinessOutputError("Public summary protocols must be a list")
    for record in protocols:
        if not isinstance(record, dict):
            raise StaleReadinessOutputError("Public summary records must be objects")
        issue = record["companion_issue"]
        title = record["title"]
        lines.append(
            f"| [{title}](https://github.com/D-sorganization/AffineDrift/issues/{issue}) "
            f"| `{record['state']}` | `{record['evidence_origin']}` "
            f"| `{record['next_gate']}` |"
        )
    lines.extend(
        [
            "",
            "All eight entries are capped at **simulation-ready**. The catalog reports ",
            "evidence state; it never authorizes participant collection or claim promotion.",
            "",
        ]
    )
    return "\n".join(lines)


def _write_or_check(path: Path, content: str, check: bool) -> None:
    if check:
        if not path.is_file() or path.read_text(encoding="utf-8") != content:
            raise StaleReadinessOutputError(f"Generated readiness output is stale: {path}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")


def generate(*, check: bool) -> list[Path]:
    """Generate or verify all deterministic readiness artifacts."""
    dictionary = _json(manufactured_dictionary())
    dry_runs = _json(manufactured_dry_runs())
    _write_or_check(DICTIONARY, dictionary, check)
    _write_or_check(DRY_RUNS, dry_runs, check)
    library = build_manufactured_library(ROOT)
    validate_library(library, SCHEMA, CLAIMS, CRITIQUES, ROOT)
    summary = build_public_summary(library)
    template = concept_template(library)
    validate_library(template, SCHEMA, CLAIMS, CRITIQUES, ROOT)
    outputs = {
        LIBRARY: _json(library),
        TEMPLATE: _json(template),
        SUMMARY: _json(summary),
        PARTIAL: _partial(summary),
    }
    for path, content in outputs.items():
        _write_or_check(path, content, check)
    return [DICTIONARY, DRY_RUNS, *outputs]


def main() -> None:
    """Run the readiness generator CLI."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if output is stale")
    args = parser.parse_args()
    try:
        generate(check=args.check)
    except (StaleReadinessOutputError, ValueError) as exc:
        parser.error(str(exc))


if __name__ == "__main__":
    main()
