"""Generate the planar swing viewer's trajectory from the teaching model (#4540).

WEB-06.10 Phase 1. The viewer animates a precomputed run of the rigid
three-link model in ``src/affine_control/golf_model.py``. Per ADR 0002 a
precomputed trajectory needs no JavaScript physics: the browser only draws
the frames written here, so the science has one source.

The run starts at rest at a declared top-of-backswing pose and applies a
declared, illustrative constant torque schedule with a passive wrist. It
stops when the club link first points straight down, which stands in for
impact. For each frame the joint accelerations split exactly into a drift
part (``GolfModel.drift_acceleration``, zero torque) and an input part
(``M(q)^-1 u``). The viewer colours each link by the input share of its
absolute angular acceleration.

Nothing here is measured. The torques are not fitted to a golfer, and the
model is planar with a rigid shaft.
"""

from __future__ import annotations

import argparse
import json
import logging
import math
from pathlib import Path

import numpy as np
from numpy.typing import NDArray

from src.affine_control.golf_model import GolfModel
from src.core.contracts import require

logger = logging.getLogger(__name__)

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "js" / "swing-viewer-data.js"

MODEL = GolfModel()
Q0_DEG = (124.0, 35.0, -95.0)
TORQUE_NM = (100.0, 30.0, 0.0)
DT = 0.001
MAX_TIME = 0.6
FRAME_STRIDE = 5
IMPACT_ANGLE = 1.5 * math.pi
DIGITS = 6

type Array = NDArray[np.float64]


def _derivative(state: Array) -> Array:
    """``[qdot, qddot]`` of the driven model: drift plus input acceleration."""
    q, qd = state[:3], state[3:]
    return np.concatenate([qd, MODEL.forced_acceleration(q, qd, np.asarray(TORQUE_NM))])


def _rk4(state: Array) -> Array:
    """One fixed-step RK4 step of length ``DT``."""
    k1 = _derivative(state)
    k2 = _derivative(state + 0.5 * DT * k1)
    k3 = _derivative(state + 0.5 * DT * k2)
    k4 = _derivative(state + DT * k3)
    return state + (DT / 6.0) * (k1 + 2 * k2 + 2 * k3 + k4)


def joint_points(q: Array) -> list[list[float]]:
    """Hub, two joints and club tip in metres, rounded for the data module."""
    return [[round(float(v), DIGITS) for v in point] for point in MODEL.joint_positions(q)]


def input_shares(q: Array, qd: Array) -> list[float]:
    """Input share of each link's absolute angular acceleration, in ``[0, 1]``."""
    drift = np.cumsum(MODEL.drift_acceleration(q, qd))
    pushed = np.cumsum(MODEL.input_acceleration(q, np.asarray(TORQUE_NM)))
    total = np.abs(drift) + np.abs(pushed)
    return [
        round(float(p / t), 4) if t > 0 else 0.0 for p, t in zip(np.abs(pushed), total, strict=True)
    ]


def simulate() -> list[dict[str, object]]:
    """Frames from the declared start until the club link points straight down."""
    state = np.concatenate([np.radians(Q0_DEG), np.zeros(3)])
    frames: list[dict[str, object]] = []
    steps = round(MAX_TIME / DT)
    for step in range(steps + 1):
        q, qd = state[:3], state[3:]
        at_impact = MODEL.link_angles(q)[2] >= IMPACT_ANGLE
        if step % FRAME_STRIDE == 0 or at_impact:
            frames.append(
                {
                    "t": round(step * DT, DIGITS),
                    "q": [round(float(v), DIGITS) for v in q],
                    "qd": [round(float(v), DIGITS) for v in qd],
                    "points": joint_points(q),
                    "inputShare": input_shares(q, qd),
                    "clubheadSpeed": round(MODEL.clubhead_speed(q, qd), 3),
                }
            )
        if at_impact:
            return frames
        state = _rk4(state)
    raise AssertionError("the club never reached the impact angle within MAX_TIME")


def build_payload() -> dict[str, object]:
    """Model metadata, declared inputs and frames for the viewer."""
    frames = simulate()
    require(len(frames) > 10, "the run must produce an animation", len(frames))
    return {
        "label": (
            "Planar (2D) rigid three-link teaching model. The shaft is rigid: "
            "nothing here bends. Torques are illustrative, not measured."
        ),
        "source": "src/affine_control/golf_model.py",
        "generator": "scripts/generate_swing_viewer_data.py",
        "issue": 4540,
        "lengthsM": list(MODEL.lengths),
        "q0Deg": list(Q0_DEG),
        "torqueNm": list(TORQUE_NM),
        "dt": DT,
        "frameStride": FRAME_STRIDE,
        "frames": frames,
    }


def render(payload: dict[str, object]) -> str:
    """JavaScript module exposing the payload to the page and to Jest."""
    body = json.dumps(payload, separators=(",", ":"), sort_keys=True)
    return (
        "// Generated by scripts/generate_swing_viewer_data.py (#4540). Do not edit.\n"
        f"(function (root) {{\n  var data = {body};\n"
        "  if (typeof module !== 'undefined' && module.exports) module.exports = data;\n"
        "  else root.AffineDriftSwingViewerData = data;\n"
        "})(typeof self !== 'undefined' ? self : this);\n"
    )


def stale() -> bool:
    """Whether the committed data module differs from a fresh build."""
    return not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != render(build_payload())


def main(argv: list[str] | None = None) -> int:
    """Write the data module, or with ``--check`` fail when it is stale."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    if args.check:
        if stale():
            logger.error("%s is stale; run python -m scripts.generate_swing_viewer_data", OUTPUT)
            return 1
        return 0
    OUTPUT.write_text(render(build_payload()), encoding="utf-8", newline="\n")
    logger.info("wrote %s", OUTPUT.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
