#!/usr/bin/env python3
"""Generate the LaTeX fragments for textbook worked examples that carry numbers.

Issue #3518 found that essentially every worked numerical example in Geometry of
Motion was unreproducible from its own stated model, because the numbers were
typed into the source by hand. Volume I chapter 6 was the worst case: a closed
loop declared "verified stable" had spectral radius 1.043.

Rather than retyping corrected numbers -- which reintroduces the same failure
mode one revision later -- each example here is solved, and the chapter
``\\input``s the result. Run with ``--check`` in CI to fail when a committed
fragment no longer matches what the code produces.

    python3 scripts/generate_worked_examples.py           # write
    python3 scripts/generate_worked_examples.py --check    # verify freshness
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.affine_control.dynamics import christoffel_coriolis, planar_double_pendulum_trajectory
from src.affine_control.golf_model import SEGMENTS, GolfModel
from src.affine_control.lqr import LQRSolution, discrete_lqr
from src.affine_control.rnea import PlanarChain, PlanarLink

REPO_ROOT = Path(__file__).resolve().parent.parent
GENERATED_DIR = REPO_ROOT / "articles/The_Geometry_of_Motion/Volume_I/generated"

BANNER = (
    "% DO NOT EDIT. Generated by scripts/generate_worked_examples.py.\n"
    "% Every number below is solved, not transcribed; CI fails if this file\n"
    "% drifts from what the generator produces (issue #3518).\n"
)

# Linearised inverted pendulum, dt = 0.1 s, g/l = 9.81.
CH06_A = np.array([[1.0, 0.1], [0.981, 1.0]])
CH06_B = np.array([[0.005], [0.1]])
CH06_Q = np.diag([10.0, 1.0])
CH06_R = np.array([[0.1]])
CH06_X0 = np.array([1.0, 0.0])
CH06_STEPS = 10
# Bound published for the Riccati residual. The observed value is order 1e-14 --
# machine precision -- so the number itself is not portable; the guarantee is.
CH06_RESIDUAL_TOLERANCE = 1e-10


def _clean(values: np.ndarray, tolerance: float = 5e-5) -> np.ndarray:
    """Snap values below the printing tolerance to exactly zero.

    Orthogonal mode shapes give an off-diagonal modal mass of order 1e-17, which
    would otherwise typeset as ``-0.0000`` and read as a rounding artefact rather
    than the exact zero it is.
    """
    cleaned = np.array(values, dtype=float, copy=True)
    cleaned[np.abs(cleaned) < tolerance] = 0.0
    return cleaned


def _matrix(values: np.ndarray, fmt: str = "{:.4f}") -> str:
    rows = [" & ".join(fmt.format(v) for v in row) for row in np.atleast_2d(_clean(values))]
    return " \\\\ ".join(rows)


def _row_vector(values: np.ndarray, fmt: str = "{:.4f}") -> str:
    return " & ".join(fmt.format(v) for v in _clean(values).reshape(-1))


def render_ch06(solution: LQRSolution) -> str:
    """Emit every quantity ch06's worked example quotes."""
    eig_s = solution.eigenvalues_riccati()
    eig_cl = np.sort(np.real_if_close(solution.eigenvalues_closed_loop()))
    stage = solution.stage_cost(CH06_Q, CH06_R)
    stage_eig = np.linalg.eigvalsh(stage)
    rho = solution.contraction_rate(CH06_Q, CH06_R)
    residual = solution.residual(CH06_A, CH06_B, CH06_Q, CH06_R)
    rows = solution.value_trajectory(CH06_X0, CH06_STEPS)

    lines = [BANNER, ""]

    def macro(name: str, body: str) -> None:
        lines.append(f"\\newcommand{{\\{name}}}{{{body}}}")

    macro("chsixRiccati", _matrix(solution.riccati))
    macro("chsixRiccatiEigMax", f"{eig_s.max():.4f}")
    macro("chsixRiccatiEigMin", f"{eig_s.min():.4f}")
    macro("chsixCondition", f"{solution.condition_number():.4f}")
    macro("chsixGain", _row_vector(solution.gain))
    macro("chsixGainAngle", f"{solution.gain.reshape(-1)[0]:.4f}")
    macro("chsixGainRate", f"{solution.gain.reshape(-1)[1]:.4f}")
    macro("chsixBtS", _row_vector(CH06_B.T @ solution.riccati))
    macro("chsixBtSA", _row_vector(CH06_B.T @ solution.riccati @ CH06_A))
    b_t_s_b = float((CH06_B.T @ solution.riccati @ CH06_B).item())
    macro("chsixBtSB", f"{b_t_s_b:.5f}")
    macro("chsixRplusBtSB", f"{float(CH06_R.item()) + b_t_s_b:.5f}")
    macro("chsixBK", _matrix(CH06_B @ solution.gain))
    macro("chsixClosedLoop", _matrix(solution.closed_loop))
    macro("chsixEigOne", f"{eig_cl[0]:.4f}")
    macro("chsixEigTwo", f"{eig_cl[1]:.4f}")
    macro("chsixSpectralRadius", f"{solution.spectral_radius():.4f}")
    macro("chsixStageCost", _matrix(stage))
    macro("chsixStageEigMax", f"{stage_eig.max():.4f}")
    macro("chsixStageEigMin", f"{stage_eig.min():.4f}")
    macro("chsixRho", f"{rho:.4f}")
    macro("chsixSqrtCondition", f"{np.sqrt(solution.condition_number()):.4f}")
    # A bound, not the measured residual. The residual is at machine precision
    # (order 1e-14) and its exact value depends on the BLAS, so pinning it makes
    # the committed fragment fail the freshness gate on a different machine than
    # the one that wrote it -- which is exactly what happened on CI.
    if residual > CH06_RESIDUAL_TOLERANCE:
        raise ValueError(
            f"Riccati residual {residual:.2e} exceeds the published tolerance "
            f"of {CH06_RESIDUAL_TOLERANCE:.0e}"
        )
    macro("chsixRiccatiResidual", f"{CH06_RESIDUAL_TOLERANCE:.0e}")
    macro("chsixValueRatioTen", f"{rows[-1][1] / rows[0][1]:.4f}")
    macro("chsixBoundTen", f"{rho ** CH06_STEPS:.4f}")

    lines.append("")
    lines.append("\\newcommand{\\chsixValueTable}{%")
    lines.append("\\begin{tabular}{|c|c|c|c|c|}")
    lines.append("\\hline")
    lines.append(
        "Step $k$ & $V_k$ & $\\norm{\\dx_k}$ & $V_k/V_{k-1}$ (actual) " "& $\\rho^k$ (bound) \\\\"
    )
    lines.append("\\hline")
    previous: float | None = None
    for k, value, norm in rows:
        ratio = "---" if previous is None else f"{value / previous:.4f}"
        lines.append(f"{k} & {value:.4f} & {norm:.4f} & {ratio} & {rho**k:.4f} \\\\")
        previous = value
    lines.append("\\hline")
    lines.append("\\end{tabular}%")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


CH08_CONFIGURATION_DEGREES = (60.0, -30.0, -20.0)
# Mid-downswing segment rates. Measured peak values are of order 10-30 rad/s,
# with the wrist fastest; anything near 100 rad/s is roughly 1000 rpm and does
# not occur in a golf swing.
CH08_VELOCITY = (12.0, -18.0, -25.0)


def render_ch08(model: GolfModel) -> str:
    """Emit the chapter 8 golf mass matrix, coupling, Schur complement and mobility."""
    q = np.deg2rad(np.array(CH08_CONFIGURATION_DEGREES))
    m_qq = model.rigid_mass_matrix(q)
    m_qeta, m_etaeta = model.shaft_blocks(q)
    schur = model.schur_complement(q)
    mobility = model.effective_mobility(q)

    lines = [BANNER, ""]

    def macro(name: str, body: str) -> None:
        lines.append(f"\\newcommand{{\\{name}}}{{{body}}}")

    # The segment parameters themselves, so the chapter's stated inputs cannot
    # drift from the model that consumes them.
    names = ("One", "Two", "Three")
    for index, label in enumerate(names):
        macro(f"cheightMass{label}", f"{model.masses[index]:g}")
        macro(f"cheightLength{label}", f"{model.lengths[index]:.2f}")
        macro(f"cheightInertia{label}", f"{model.inertias[index]:g}")
    macro("cheightShaftMass", f"{model.shaft_mass:g}")
    macro("cheightClubheadSpeed", f"{model.clubhead_speed(q, np.array(CH08_VELOCITY)):.2f}")

    macro("cheightMqq", _matrix(m_qq))
    macro("cheightMqqDet", f"{np.linalg.det(m_qq):.4f}")
    macro("cheightMqqEigMin", f"{np.linalg.eigvalsh(m_qq).min():.4f}")
    macro("cheightMqqEigMax", f"{np.linalg.eigvalsh(m_qq).max():.4f}")
    macro("cheightMqeta", _matrix(m_qeta))
    macro("cheightMetaeta", _matrix(m_etaeta))
    macro("cheightMetaetaInv", _matrix(np.linalg.inv(m_etaeta), fmt="{:.2f}"))
    macro("cheightCoupling", _matrix(m_qeta @ np.linalg.solve(m_etaeta, m_qeta.T)))
    macro("cheightSchur", _matrix(schur))
    macro("cheightSchurEigMin", f"{np.linalg.eigvalsh(schur).min():.4f}")
    macro("cheightSchurEigMax", f"{np.linalg.eigvalsh(schur).max():.4f}")
    macro("cheightMobility", _matrix(mobility))
    macro("cheightMobilityEigMin", f"{np.linalg.eigvalsh(mobility).min():.4f}")
    macro("cheightFullEigMin", f"{np.linalg.eigvalsh(model.full_mass_matrix(q)).min():.4f}")

    # Drift acceleration at a physically plausible mid-downswing velocity.
    # Peak segment rates in a real downswing are of order 10-30 rad/s; the
    # earlier revision used 50 to 100 rad/s, which is several times faster than
    # any measured swing and inflated the Coriolis term accordingly.
    qd = np.array(CH08_VELOCITY)
    bias = model.coriolis(q, qd) @ qd + model.gravity_torque(q)
    macro("cheightVelocity", _row_vector(qd, fmt="{:.0f}"))
    macro("cheightBias", _row_vector(bias, fmt="{:.2f}"))
    macro("cheightDriftAccel", _row_vector(model.drift_acceleration(q, qd), fmt="{:.2f}"))
    gravity = model.gravity_torque(q)
    coriolis = model.coriolis(q, qd) @ qd
    macro("cheightGravity", _row_vector(gravity, fmt="{:.2f}"))
    macro("cheightCoriolisTerm", _row_vector(coriolis, fmt="{:.2f}"))
    # Individual components, so the surrounding prose does not have to retype
    # numbers it is discussing.
    macro("cheightCoriolisShoulder", f"{coriolis[0]:.2f}")
    macro("cheightGravityShoulder", f"{gravity[0]:.2f}")

    # ZTCF trajectory: integrate with zero applied torque from the state above.
    trajectory = model.ztcf_trajectory(q, qd, duration=0.10, steps=400)
    sampled = [trajectory[0], trajectory[len(trajectory) // 2], trajectory[-1]]
    lines.append("")
    lines.append("\\newcommand{\\cheightZtcfTable}{%")
    lines.append("\\begin{tabular}{@{}ccccc@{}}")
    lines.append("\\toprule")
    lines.append(
        "$t$ (s) & $q_3$ (rad) & $\\dot q_3$ (rad/s) & "
        "Clubhead speed (m/s) & $\\rho_{\\text{DCR}}$ \\\\"
    )
    lines.append("\\midrule")
    for time, pos, vel, speed in sampled:
        drift = np.linalg.norm(model.drift_acceleration(pos, vel))
        lines.append(f"{time:.3f} & {pos[2]:.4f} & {vel[2]:.2f} & {speed:.2f} & {drift:.1f} \\\\")
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}%")
    lines.append("}")
    macro("cheightZtcfSpeedStart", f"{sampled[0][3]:.2f}")
    macro("cheightZtcfSpeedEnd", f"{sampled[-1][3]:.2f}")
    macro(
        "cheightZtcfSpeedGain",
        f"{100.0 * (sampled[-1][3] / sampled[0][3] - 1.0):.1f}",
    )
    lines.append("")
    return "\n".join(lines)


# Volume I chapter 7: planar double pendulum, m1 = m2 = 1, l1 = l2 = 1, g = 9.81.
CH07_TORQUE = 5.0
CH07_HORIZON = 2.0
CH07_STEPS = 5_000
CH07_SAMPLE_TIMES = (0.0, 0.5, 1.0, 1.5, 2.0)
GRAVITY_M_S2 = 9.81


def ch07_mass_matrix(q: np.ndarray) -> np.ndarray:
    """M(q) as printed at eq:ch7:mass-matrix-numeric."""
    c = np.cos(q[0] - q[1])
    return np.array([[2.0, c], [c, 1.0]])


def ch07_grad_potential(q: np.ndarray) -> np.ndarray:
    """dV/dq for V = -g cos q1 - g (cos q1 + cos q2)."""
    return np.array([2.0 * GRAVITY_M_S2 * np.sin(q[0]), GRAVITY_M_S2 * np.sin(q[1])])


def render_ch07() -> str:
    """Emit the chapter 7 ZTCF-versus-actual comparison, actually integrated."""
    q0 = np.array([np.pi / 4, np.pi / 6])
    qd0 = np.array([2.0, -1.0])

    def trajectory(torque: float) -> dict[float, tuple[np.ndarray, np.ndarray]]:
        rows = planar_double_pendulum_trajectory(
            ch07_mass_matrix,
            ch07_grad_potential,
            q0,
            qd0,
            np.array([torque, 0.0]),
            CH07_HORIZON,
            CH07_STEPS,
        )
        step = CH07_STEPS // int(CH07_HORIZON / (CH07_SAMPLE_TIMES[1] - CH07_SAMPLE_TIMES[0]))
        return {
            round(rows[i * step][0], 3): rows[i * step][1:] for i in range(len(CH07_SAMPLE_TIMES))
        }

    actual = trajectory(CH07_TORQUE)
    ztcf = trajectory(0.0)

    lines = [BANNER, ""]

    def macro(name: str, body: str) -> None:
        lines.append(f"\\newcommand{{\\{name}}}{{{body}}}")

    lines.append("\\newcommand{\\chsevenTrajectoryTable}{%")
    lines.append("\\begin{tabular}{|c|c|c|c|c|c|c|c|}")
    lines.append("\\hline")
    lines.append(
        "$t$ (s) & $q_1$ & $q_2$ & $\\dot q_1$ & $\\dot q_2$ & "
        "$a_{\\text{drift},1}$ & $\\tau_1[M^{-1}]_{11}$ & $\\rho(t)$ \\\\"
    )
    lines.append("\\hline")
    separations = []
    for time in CH07_SAMPLE_TIMES:
        q, qd = actual[time]
        bias = christoffel_coriolis(ch07_mass_matrix, q, qd) @ qd + ch07_grad_potential(q)
        drift = -np.linalg.solve(ch07_mass_matrix(q), bias)
        control = CH07_TORQUE * np.linalg.inv(ch07_mass_matrix(q))[0, 0]
        ratio = abs(drift[0]) / abs(control)
        lines.append(
            f"{time:.1f} & {q[0]:.4f} & {q[1]:.4f} & {qd[0]:.4f} & {qd[1]:.4f} & "
            f"{drift[0]:.3f} & {control:.3f} & {ratio:.3f} \\\\"
        )
        separations.append(float(np.linalg.norm(q - ztcf[time][0])))
    lines.append("\\hline")
    lines.append("\\end{tabular}%")
    lines.append("}")
    lines.append("")

    lines.append("\\newcommand{\\chsevenZtcfTable}{%")
    lines.append("\\begin{tabular}{|c|c|c|c|c|c|}")
    lines.append("\\hline")
    lines.append(
        "$t$ (s) & $q_1$ & $q_2$ & $\\dot q_1$ & $\\dot q_2$ & "
        "$\\lVert \\Delta \\bm{q}\\rVert$ \\\\"
    )
    lines.append("\\hline")
    for time, separation in zip(CH07_SAMPLE_TIMES, separations, strict=True):
        q, qd = ztcf[time]
        lines.append(
            f"{time:.1f} & {q[0]:.4f} & {q[1]:.4f} & {qd[0]:.4f} & {qd[1]:.4f} & "
            f"{separation:.4f} \\\\"
        )
    lines.append("\\hline")
    lines.append("\\end{tabular}%")
    lines.append("}")
    lines.append("")

    macro("chsevenSeparationHalf", f"{separations[1]:.4f}")
    macro("chsevenSeparationFinal", f"{separations[-1]:.4f}")
    macro("chsevenTorque", f"{CH07_TORQUE:.0f}")
    macro("chsevenSteps", f"{CH07_STEPS:,}")

    # Gravity-versus-Coriolis decomposition at the mid-trajectory sample, which
    # the prose below the table discusses.
    q_mid, qd_mid = actual[1.0]
    inverse = np.linalg.inv(ch07_mass_matrix(q_mid))
    grav = -inverse @ ch07_grad_potential(q_mid)
    cor = -inverse @ (christoffel_coriolis(ch07_mass_matrix, q_mid, qd_mid) @ qd_mid)
    macro("chsevenMidQOne", f"{q_mid[0]:.4f}")
    macro("chsevenMidQTwo", f"{q_mid[1]:.4f}")
    macro("chsevenMidRateOne", f"{qd_mid[0]:.4f}")
    macro("chsevenMidRateTwo", f"{qd_mid[1]:.4f}")
    macro("chsevenMidGravity", _row_vector(grav, fmt="{:.3f}"))
    macro("chsevenMidCoriolis", _row_vector(cor, fmt="{:.3f}"))
    macro("chsevenMidDrift", _row_vector(grav + cor, fmt="{:.3f}"))
    lines.append("")
    return "\n".join(lines)


VOL0_GENERATED_DIR = REPO_ROOT / "articles/The_Geometry_of_Motion/Volume_0/generated"

# Volume 0 chapter 7's worked RNEA example, exactly as the chapter specifies it.
VOL0_CH07_CHAIN = PlanarChain(
    (
        PlanarLink(mass=1.0, length=1.0, com_offset=0.5, inertia=0.083),
        PlanarLink(mass=0.5, length=0.8, com_offset=0.4, inertia=0.027),
        PlanarLink(mass=0.2, length=0.6, com_offset=0.6, inertia=0.0),
    )
)
VOL0_CH07_Q = np.array([0.524, 0.785, 0.0])
VOL0_CH07_QD = np.array([0.5, 0.3, 0.2])
VOL0_CH07_QDD = np.array([1.0, 0.5, 0.1])
# The bound the chapter publishes for the RNEA-versus-Lagrangian cross-check.
# Comfortably above the observed residual (~1e-9, dominated by the central
# differences in the Coriolis and gravity terms) and far below anything that
# would indicate a real disagreement.
VOL0_RNEA_TOLERANCE = 1e-8


def render_vol0_ch07() -> str:
    """Emit the Volume 0 chapter 7 RNEA torques, computed both ways."""
    chain = VOL0_CH07_CHAIN
    recursive = chain.inverse_dynamics(VOL0_CH07_Q, VOL0_CH07_QD, VOL0_CH07_QDD)
    lagrangian = chain.inverse_dynamics_lagrangian(VOL0_CH07_Q, VOL0_CH07_QD, VOL0_CH07_QDD)

    lines = [BANNER, ""]

    def macro(name: str, body: str) -> None:
        lines.append(f"\\newcommand{{\\{name}}}{{{body}}}")

    agreement = float(np.abs(recursive - lagrangian).max())
    if agreement > VOL0_RNEA_TOLERANCE:
        raise ValueError(
            f"RNEA and Lagrangian routes disagree by {agreement:.2e}, "
            f"above the published tolerance of {VOL0_RNEA_TOLERANCE:.0e}"
        )

    macro("volzeroRneaTorque", _row_vector(recursive, fmt="{:.3f}"))
    macro("volzeroLagrangianTorque", _row_vector(lagrangian, fmt="{:.3f}"))
    # A fixed bound, not the measured residual. The residual is the difference
    # of two nearly-equal floats -- around 1e-9 -- so its exact value depends on
    # the BLAS and the platform, and pinning it made the committed fragment fail
    # the freshness gate on a different machine than the one that wrote it.
    macro("volzeroRneaAgreement", f"{VOL0_RNEA_TOLERANCE:.0e}")
    macro("volzeroRneaTorqueOne", f"{recursive[0]:.3f}")
    macro("volzeroRneaTorqueThree", f"{recursive[2]:.3f}")
    lines.append("")
    return "\n".join(lines)


CH10_SOURCE = REPO_ROOT / "src/affine_control/swing_analysis.py"
CH10_GENERATED_DIR = REPO_ROOT / "articles/The_Geometry_of_Motion/Volume_V/generated"


def render_ch10() -> str:
    """Wrap the real swing-analysis module as a LaTeX listing.

    Volume V chapter 10 printed this pipeline as a hand-maintained listing that
    was never executed, and three parts of it did not work. Emitting the listing
    from the module means the chapter shows exactly the code CI runs, and the
    ``--check`` gate fails if the two drift apart.

    ``lstinputlisting`` would be the more direct mechanism, but nothing else in
    the corpus uses it and it would put a build-time dependency on a path outside
    the article tree, which the PDF workflow has never exercised. Generating the
    listing keeps the LaTeX side identical to the other chapters.
    """
    source = CH10_SOURCE.read_text(encoding="utf-8").rstrip("\n")
    return "\n".join(
        [
            BANNER,
            "",
            "\\begin{lstlisting}[language=Python, caption={Golf swing analysis pipeline, "
            "generated from \\texttt{src/affine\\_control/swing\\_analysis.py}.}]",
            source,
            "\\end{lstlisting}",
            "",
        ]
    )


def build() -> dict[Path, str]:
    """Return the full set of generated fragments, keyed by destination path."""
    solution = discrete_lqr(CH06_A, CH06_B, CH06_Q, CH06_R)
    return {
        GENERATED_DIR / "ch06_lqr_example.tex": render_ch06(solution),
        GENERATED_DIR / "ch07_double_pendulum.tex": render_ch07(),
        GENERATED_DIR / "ch08_golf_model.tex": render_ch08(SEGMENTS),
        CH10_GENERATED_DIR / "ch10_swing_analysis.tex": render_ch10(),
        VOL0_GENERATED_DIR / "ch07_rnea_example.tex": render_vol0_ch07(),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the committed fragments match the generator; do not write",
    )
    args = parser.parse_args()

    artifacts = build()
    stale: list[Path] = []

    for path, content in artifacts.items():
        if args.check:
            current = path.read_text(encoding="utf-8") if path.exists() else None
            if current != content:
                stale.append(path)
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"wrote {path.relative_to(REPO_ROOT).as_posix()}")

    if args.check:
        if stale:
            for path in stale:
                rel = path.relative_to(REPO_ROOT).as_posix()
                print(f"::error::{rel} is stale or missing", file=sys.stderr)
            print(
                "\nRegenerate with: python3 scripts/generate_worked_examples.py",
                file=sys.stderr,
            )
            return 1
        print(f"{len(artifacts)} generated fragment(s) up to date.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
