#!/usr/bin/env python3
"""Generate the LaTeX fragments for textbook worked examples that carry numbers.

Issue #3518 found that essentially every worked numerical example in Geometry of
Motion was unreproducible from its own stated model, because the numbers were
typed into the source by hand. Volume I chapter 6 was the worst case: a closed
loop declared "verified stable" had spectral radius 1.043.

Rather than retyping corrected numbers -- which reintroduces the same failure
mode one revision later -- each example here is solved, and the chapter
``\\input``s the result. Run with ``--check`` in CI to fail when a committed
fragment no longer matches what the code produces.

    python3 scripts/generate_worked_examples.py           # write
    python3 scripts/generate_worked_examples.py --check    # verify freshness
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.affine_control.lqr import LQRSolution, discrete_lqr

REPO_ROOT = Path(__file__).resolve().parent.parent
GENERATED_DIR = REPO_ROOT / "articles/The_Geometry_of_Motion/Volume_I/generated"

BANNER = (
    "% DO NOT EDIT. Generated by scripts/generate_worked_examples.py.\n"
    "% Every number below is solved, not transcribed; CI fails if this file\n"
    "% drifts from what the generator produces (issue #3518).\n"
)

# Linearised inverted pendulum, dt = 0.1 s, g/l = 9.81.
CH06_A = np.array([[1.0, 0.1], [0.981, 1.0]])
CH06_B = np.array([[0.005], [0.1]])
CH06_Q = np.diag([10.0, 1.0])
CH06_R = np.array([[0.1]])
CH06_X0 = np.array([1.0, 0.0])
CH06_STEPS = 10


def _matrix(values: np.ndarray, fmt: str = "{:.4f}") -> str:
    rows = [" & ".join(fmt.format(v) for v in row) for row in np.atleast_2d(values)]
    return " \\\\ ".join(rows)


def _row_vector(values: np.ndarray, fmt: str = "{:.4f}") -> str:
    return " & ".join(fmt.format(v) for v in np.asarray(values).reshape(-1))


def render_ch06(solution: LQRSolution) -> str:
    """Emit every quantity ch06's worked example quotes."""
    eig_s = solution.eigenvalues_riccati()
    eig_cl = np.sort(np.real_if_close(solution.eigenvalues_closed_loop()))
    stage = solution.stage_cost(CH06_Q, CH06_R)
    stage_eig = np.linalg.eigvalsh(stage)
    rho = solution.contraction_rate(CH06_Q, CH06_R)
    residual = solution.residual(CH06_A, CH06_B, CH06_Q, CH06_R)
    rows = solution.value_trajectory(CH06_X0, CH06_STEPS)

    lines = [BANNER, ""]

    def macro(name: str, body: str) -> None:
        lines.append(f"\\newcommand{{\\{name}}}{{{body}}}")

    macro("chsixRiccati", _matrix(solution.riccati))
    macro("chsixRiccatiEigMax", f"{eig_s.max():.4f}")
    macro("chsixRiccatiEigMin", f"{eig_s.min():.4f}")
    macro("chsixCondition", f"{solution.condition_number():.4f}")
    macro("chsixGain", _row_vector(solution.gain))
    macro("chsixGainAngle", f"{solution.gain.reshape(-1)[0]:.4f}")
    macro("chsixGainRate", f"{solution.gain.reshape(-1)[1]:.4f}")
    macro("chsixBtS", _row_vector(CH06_B.T @ solution.riccati))
    macro("chsixBtSA", _row_vector(CH06_B.T @ solution.riccati @ CH06_A))
    b_t_s_b = float((CH06_B.T @ solution.riccati @ CH06_B).item())
    macro("chsixBtSB", f"{b_t_s_b:.5f}")
    macro("chsixRplusBtSB", f"{float(CH06_R.item()) + b_t_s_b:.5f}")
    macro("chsixBK", _matrix(CH06_B @ solution.gain))
    macro("chsixClosedLoop", _matrix(solution.closed_loop))
    macro("chsixEigOne", f"{eig_cl[0]:.4f}")
    macro("chsixEigTwo", f"{eig_cl[1]:.4f}")
    macro("chsixSpectralRadius", f"{solution.spectral_radius():.4f}")
    macro("chsixStageCost", _matrix(stage))
    macro("chsixStageEigMax", f"{stage_eig.max():.4f}")
    macro("chsixStageEigMin", f"{stage_eig.min():.4f}")
    macro("chsixRho", f"{rho:.4f}")
    macro("chsixSqrtCondition", f"{np.sqrt(solution.condition_number()):.4f}")
    macro("chsixRiccatiResidual", f"{residual:.2e}")
    macro("chsixValueRatioTen", f"{rows[-1][1] / rows[0][1]:.4f}")
    macro("chsixBoundTen", f"{rho ** CH06_STEPS:.4f}")

    lines.append("")
    lines.append("\\newcommand{\\chsixValueTable}{%")
    lines.append("\\begin{tabular}{|c|c|c|c|c|}")
    lines.append("\\hline")
    lines.append(
        "Step $k$ & $V_k$ & $\\norm{\\dx_k}$ & $V_k/V_{k-1}$ (actual) " "& $\\rho^k$ (bound) \\\\"
    )
    lines.append("\\hline")
    previous: float | None = None
    for k, value, norm in rows:
        ratio = "---" if previous is None else f"{value / previous:.4f}"
        lines.append(f"{k} & {value:.4f} & {norm:.4f} & {ratio} & {rho**k:.4f} \\\\")
        previous = value
    lines.append("\\hline")
    lines.append("\\end{tabular}%")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def build() -> dict[Path, str]:
    """Return the full set of generated fragments, keyed by destination path."""
    solution = discrete_lqr(CH06_A, CH06_B, CH06_Q, CH06_R)
    return {GENERATED_DIR / "ch06_lqr_example.tex": render_ch06(solution)}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the committed fragments match the generator; do not write",
    )
    args = parser.parse_args()

    artifacts = build()
    stale: list[Path] = []

    for path, content in artifacts.items():
        if args.check:
            current = path.read_text(encoding="utf-8") if path.exists() else None
            if current != content:
                stale.append(path)
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"wrote {path.relative_to(REPO_ROOT).as_posix()}")

    if args.check:
        if stale:
            for path in stale:
                rel = path.relative_to(REPO_ROOT).as_posix()
                print(f"::error::{rel} is stale or missing", file=sys.stderr)
            print(
                "\nRegenerate with: python3 scripts/generate_worked_examples.py",
                file=sys.stderr,
            )
            return 1
        print(f"{len(artifacts)} generated fragment(s) up to date.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
