"""Generate the shared reader definitions from the canonical maturity vocabulary."""

from __future__ import annotations

import argparse
import logging
from pathlib import Path

from src.tools.utils.maturity import (
    CanonicalMaturityState,
    MaturityVocabulary,
    load_maturity_config,
)

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "_includes/generated/publication-states.qmd"
LOGGER = logging.getLogger(__name__)


def render_definitions(vocabulary: MaturityVocabulary) -> str:
    """Return all canonical definitions and limits; reject incomplete vocabulary."""
    if set(vocabulary.states) != set(CanonicalMaturityState):
        raise ValueError("Publication definitions require exactly the canonical states")
    lines = ["<!-- Generated by scripts.generate_publication_states; do not edit. -->", ""]
    for key in CanonicalMaturityState:
        state = vocabulary.states[key]
        fields = (state.label, state.definition, state.does_not_establish)
        if any(not isinstance(value, str) or not value.strip() for value in fields):
            raise ValueError("Publication labels, definitions, and limits must be non-empty")
        lines.append(f"- **{state.label}**: {state.definition} {state.does_not_establish}")
    return "\n".join(lines) + "\n"


def main() -> int:
    """Write the derived include or fail when a checked-in include is stale."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render_definitions(load_maturity_config())
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != expected:
            LOGGER.error("Publication definitions are stale; run this module without --check")
            return 1
        return 0
    OUTPUT.write_text(expected, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
