"""Generate or verify the WEB-08.4 animated explainers (#4555).

Each explainer in ``scripts/explainer_scenes.py`` is rendered frame by frame
with Matplotlib from ``src/`` trajectories and encoded to MP4 (H.264) and WebM
(VP9) with the ffmpeg bundled by ``imageio-ffmpeg``. The run also writes a
poster image, a WebVTT caption track, an embeddable include with the
transcript, and ``data/explainers/manifest.json``, which pins the digest of
every asset and every source the frames were computed from.

Usage::

    python -m scripts.generate_explainer_videos          # render and encode everything
    python -m scripts.generate_explainer_videos --check  # fail if anything is stale

Encoding needs the ``media`` extra (``pip install -e ".[media]"``).
``--check`` does not re-encode: it verifies the text outputs, the source and
asset digests and the size budget.
"""

from __future__ import annotations

import argparse
import hashlib
import html
import json
import logging
import subprocess
import sys
from pathlib import Path
from typing import Any

from scripts.explainer_scenes import EXPLAINERS, FPS, HEIGHT, INK, WIDTH, Explainer

logger = logging.getLogger(__name__)

REPO_ROOT = Path(__file__).resolve().parents[1]
MEDIA_DIR = "static/explainers"
INCLUDE_DIR = "_includes/generated/explainers"
MANIFEST_PATH = "data/explainers/manifest.json"
#: The frame painters; every explainer depends on them as well as on its own sources.
SCENES_PATH = "scripts/explainer_scenes.py"
SCHEMA = "affinedrift/explainer-videos/v1"
GENERATOR = "python -m scripts.generate_explainer_videos"
#: WEB-08.4 acceptance: each video under 3 MB.
MAX_VIDEO_BYTES = 3 * 1024 * 1024
ASSET_SUFFIXES = {"mp4": ".mp4", "webm": ".webm", "poster": ".poster.png", "captions": ".en.vtt"}


def _sha256(path: Path) -> str:
    """SHA-256 of one file's bytes."""
    return hashlib.sha256(path.read_bytes()).hexdigest()


def asset_path(explainer: Explainer, kind: str) -> str:
    """Repository-relative path of one of ``explainer``'s assets."""
    return f"{MEDIA_DIR}/{explainer.id}{ASSET_SUFFIXES[kind]}"


def _timestamp(seconds: float) -> str:
    """WebVTT timestamp ``HH:MM:SS.mmm``."""
    millis = round(seconds * 1000)
    hours, rest = divmod(millis, 3_600_000)
    minutes, rest = divmod(rest, 60_000)
    return f"{hours:02d}:{minutes:02d}:{rest // 1000:02d}.{rest % 1000:03d}"


def render_vtt(explainer: Explainer) -> str:
    """The WebVTT caption track; cues must be ordered, non-overlapping and in range."""
    previous = 0.0
    lines = ["WEBVTT", ""]
    for index, cue in enumerate(explainer.cues, start=1):
        if not previous <= cue.start < cue.end <= explainer.duration:
            raise ValueError(f"{explainer.id}: cue {index} is out of order or out of range")
        previous = cue.end
        lines += [str(index), f"{_timestamp(cue.start)} --> {_timestamp(cue.end)}", cue.text, ""]
    return "\n".join(lines)


def render_include(explainer: Explainer) -> str:
    """Embeddable figure: no autoplay or loop, captions on, transcript alongside."""
    media = f"../{MEDIA_DIR}/{explainer.id}"
    transcript = "\n".join(f"<p>{html.escape(cue.text)}</p>" for cue in explainer.cues)
    sources = ", ".join(f"<code>{path}</code>" for path in explainer.sources)
    return f"""<!-- DO NOT EDIT. Generated by {GENERATOR}. -->

```{{=html}}
<figure class="explainer-video" id="explainer-{explainer.id}">
<video controls preload="none" playsinline width="{WIDTH}" height="{HEIGHT}" poster="{media}.poster.png" aria-describedby="explainer-{explainer.id}-transcript">
  <source src="{media}.webm" type="video/webm">
  <source src="{media}.mp4" type="video/mp4">
  <track kind="captions" src="{media}.en.vtt" srclang="en" label="English" default>
</video>
<figcaption><strong>{html.escape(explainer.title)}</strong> ({explainer.duration:.0f} s, captioned).
Exploratory model output, generated from {sources}. It does not play by itself.</figcaption>
<details id="explainer-{explainer.id}-transcript">
<summary>Transcript</summary>
{transcript}
</details>
</figure>
```
"""


def _manifest_entry(explainer: Explainer, root: Path) -> dict[str, Any]:
    """Manifest record: settings, source digests and asset digests and sizes."""
    assets = {}
    for kind in ASSET_SUFFIXES:
        path = root / asset_path(explainer, kind)
        assets[kind] = {
            "path": asset_path(explainer, kind),
            "sha256": _sha256(path),
            "bytes": path.stat().st_size,
        }
    return {
        "id": explainer.id,
        "title": explainer.title,
        "duration_s": explainer.duration,
        "fps": FPS,
        "size": {"width": WIDTH, "height": HEIGHT},
        "sources": {path: _sha256(root / path) for path in (SCENES_PATH, *explainer.sources)},
        "assets": assets,
    }


def render_manifest(root: Path = REPO_ROOT) -> str:
    """Deterministic manifest JSON over the assets currently on disk."""
    document = {
        "schema": SCHEMA,
        "generator": GENERATOR,
        "explainers": [_manifest_entry(explainer, root) for explainer in EXPLAINERS],
    }
    return json.dumps(document, indent=2) + "\n"


def _frames(explainer: Explainer) -> Any:
    """Yield RGB frames as bytes; Matplotlib renders off-screen with the Agg backend."""
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    import numpy as np

    figure = plt.figure(figsize=(WIDTH / 100, HEIGHT / 100), dpi=100)
    axes = figure.add_axes((0.0, 0.0, 1.0, 1.0))
    try:
        for index in range(round(explainer.duration * FPS)):
            yield _paint(figure, axes, explainer, index / FPS, np)
    finally:
        plt.close(figure)


def _paint(figure: Any, axes: Any, explainer: Explainer, t: float, np: Any) -> bytes:
    """Paint one frame at time ``t`` and return its RGB bytes."""
    axes.clear()
    axes.set_aspect("equal")
    axes.axis("off")
    explainer.paint(axes, t)
    axes.text(
        0.98,
        0.96,
        explainer.title,
        transform=figure.transFigure,
        ha="right",
        va="top",
        fontsize=9,
        color=INK,
    )
    figure.canvas.draw()
    return bytes(np.asarray(figure.canvas.buffer_rgba())[:, :, :3].tobytes())


def _encoders(explainer: Explainer, root: Path) -> list[subprocess.Popen[bytes]]:
    """Start one ffmpeg per container, each reading raw RGB frames from stdin."""
    import imageio_ffmpeg

    common = [imageio_ffmpeg.get_ffmpeg_exe(), "-y", "-loglevel", "error", "-f", "rawvideo"]
    common += ["-pix_fmt", "rgb24", "-s", f"{WIDTH}x{HEIGHT}", "-r", str(FPS), "-i", "-", "-an"]
    common += [
        "-map_metadata",
        "-1",
        "-fflags",
        "+bitexact",
        "-flags:v",
        "+bitexact",
        "-threads",
        "1",
    ]
    codecs = {
        "mp4": [
            "-c:v",
            "libx264",
            "-preset",
            "slow",
            "-crf",
            "26",
            "-pix_fmt",
            "yuv420p",
            "-movflags",
            "+faststart",
        ],
        "webm": [
            "-c:v",
            "libvpx-vp9",
            "-crf",
            "38",
            "-b:v",
            "0",
            "-pix_fmt",
            "yuv420p",
            "-row-mt",
            "0",
        ],
    }
    return [
        subprocess.Popen(
            [*common, *args, str(root / asset_path(explainer, kind))], stdin=subprocess.PIPE
        )
        for kind, args in codecs.items()
    ]


def encode(explainer: Explainer, root: Path = REPO_ROOT) -> None:
    """Render ``explainer`` to MP4, WebM and its poster image."""
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    import numpy as np

    (root / MEDIA_DIR).mkdir(parents=True, exist_ok=True)
    encoders = _encoders(explainer, root)
    pipes = [encoder.stdin for encoder in encoders if encoder.stdin is not None]
    if len(pipes) != len(encoders):
        raise RuntimeError("ffmpeg encoders must read frames from stdin")
    for frame in _frames(explainer):
        for pipe in pipes:
            pipe.write(frame)
    for pipe, encoder in zip(pipes, encoders, strict=True):
        pipe.close()
        if encoder.wait() != 0:
            raise RuntimeError(f"ffmpeg failed for {explainer.id}")
    figure = plt.figure(figsize=(WIDTH / 100, HEIGHT / 100), dpi=100)
    axes = figure.add_axes((0.0, 0.0, 1.0, 1.0))
    _paint(figure, axes, explainer, explainer.poster_time, np)
    figure.savefig(root / asset_path(explainer, "poster"), dpi=100, metadata={"Software": None})
    plt.close(figure)


def _text_outputs(root: Path) -> dict[Path, str]:
    """Every generated text file and its expected content, except the manifest."""
    outputs: dict[Path, str] = {}
    for explainer in EXPLAINERS:
        outputs[root / asset_path(explainer, "captions")] = render_vtt(explainer)
        outputs[root / INCLUDE_DIR / f"{explainer.id}.qmd"] = render_include(explainer)
    return outputs


def stale_outputs(root: Path = REPO_ROOT) -> list[str]:
    """Return a description of every missing, stale or oversized output."""
    problems = [
        str(path.relative_to(root))
        for path, text in _text_outputs(root).items()
        if not path.is_file() or path.read_text(encoding="utf-8") != text
    ]
    for explainer in EXPLAINERS:
        for kind in ("mp4", "webm", "poster"):
            path = root / asset_path(explainer, kind)
            if not path.is_file():
                problems.append(f"missing {path.relative_to(root)}")
            elif kind != "poster" and path.stat().st_size >= MAX_VIDEO_BYTES:
                problems.append(f"{path.relative_to(root)} is not under 3 MB")
    manifest = root / MANIFEST_PATH
    if not problems and (
        not manifest.is_file() or manifest.read_text(encoding="utf-8") != render_manifest(root)
    ):
        problems.append(f"{MANIFEST_PATH} (sources or assets changed)")
    return problems


def main(argv: list[str] | None = None) -> int:
    """Generate every explainer, or with ``--check`` report stale outputs."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if any output is stale")
    args = parser.parse_args(argv)
    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
    if args.check:
        problems = stale_outputs()
        for problem in problems:
            logger.error("Stale explainer output (run %s): %s", GENERATOR, problem)
        return 1 if problems else 0
    for path, text in _text_outputs(REPO_ROOT).items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8", newline="\n")
    for explainer in EXPLAINERS:
        logger.info("Encoding %s", explainer.id)
        encode(explainer)
    manifest = REPO_ROOT / MANIFEST_PATH
    manifest.parent.mkdir(parents=True, exist_ok=True)
    manifest.write_text(render_manifest(), encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
