#!/usr/bin/env python3
"""Generate or verify the reader-facing persona cards include.

Issue #4488 (WEB-01.3): Single source of truth in config/personas.yml.
Generates _includes/generated/persona-cards.qmd for inclusion in
resources/learning-paths.qmd and other landing pages.
"""

from __future__ import annotations

import argparse
import logging
import os
import sys
from pathlib import Path
from typing import Any

import yaml

logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
logger = logging.getLogger(__name__)

ROOT = Path(__file__).resolve().parent.parent
CONFIG_PATH = ROOT / "config" / "personas.yml"
DEFAULT_OUTPUT = ROOT / "_includes" / "generated" / "persona-cards.qmd"


def to_relative_url(target_path: str, base_dir: str = "resources") -> str:
    """Convert a repository-root-relative path to a URL relative to base_dir."""
    # Convert .md report targets to .html if applicable for reader linking
    rel = os.path.relpath(target_path, base_dir).replace("\\", "/")
    if rel.endswith(".md"):
        rel = rel[:-3] + ".html"
    return rel


def render_persona_cards(personas_data: dict[str, Any], base_dir: str = "resources") -> str:
    """Render persona cards markdown from YAML data."""
    lines: list[str] = [
        "<!-- Generated by scripts/generate_persona_cards.py. DO NOT EDIT. -->",
        "",
        "::: {.resource-grid}",
        "",
    ]

    personas = personas_data.get("personas", {})
    workflows_page_rel = to_relative_url("models/programming/workflows.html", base_dir)

    for persona_id, p in personas.items():
        name = p.get("name", persona_id.title())
        tagline = p.get("tagline", "")
        description = p.get("description", "")
        workflows = p.get("workflows", [])
        first_page = p.get("first_page", {})
        route_30min = p.get("route_30min", {})
        route_deep = p.get("route_deep", {})
        instruction_disclaimer = p.get("instruction_disclaimer")

        first_href = to_relative_url(first_page.get("path", ""), base_dir)
        first_title = first_page.get("title", "First Page")

        r30_href = to_relative_url(route_30min.get("path", ""), base_dir)
        r30_title = route_30min.get("title", "30-Minute Route")

        deep_href = to_relative_url(route_deep.get("path", ""), base_dir)
        deep_title = route_deep.get("title", "Go Deeper")

        lines.append("::: {.resource-card}")
        lines.append(f"### {name} {{#persona-{persona_id}}}")
        if tagline:
            lines.append(f"**{tagline}**")
        lines.append("")
        lines.append(description)
        lines.append("")

        if instruction_disclaimer:
            lines.append('::: {.callout-note appearance="simple"}')
            lines.append(instruction_disclaimer)
            lines.append(":::")
            lines.append("")

        lines.append(f"- **First Page:** [{first_title}]({first_href})")
        lines.append(f"- **30-Minute Route:** [{r30_title}]({r30_href})")
        lines.append(f"- **Go Deeper:** [{deep_title}]({deep_href})")
        lines.append("")

        if workflows:
            wf_tags = ", ".join(f"`{w}`" for w in workflows)
            lines.append(f"**Workflows:** [Governed Workflows]({workflows_page_rel}) ({wf_tags})")
            lines.append("")

        lines.append(f"[Start as {name} →]({first_href}){{.resource-link}}")
        lines.append(":::")
        lines.append("")

    lines.append(":::")
    lines.append("")
    return "\n".join(lines)


def generate_persona_cards(
    check: bool = False,
    output_path: Path = DEFAULT_OUTPUT,
    base_dir: str = "resources",
) -> Path:
    """Generate or check the persona cards include file."""
    if not CONFIG_PATH.exists():
        raise FileNotFoundError(f"Missing persona config: {CONFIG_PATH}")

    data = yaml.safe_load(CONFIG_PATH.read_text(encoding="utf-8"))
    content = render_persona_cards(data, base_dir=base_dir)

    if check:
        if not output_path.exists():
            raise FileNotFoundError(f"Missing generated file: {output_path}")
        existing = output_path.read_text(encoding="utf-8")
        if existing != content:
            raise ValueError(
                f"Generated file {output_path} is out of date. "
                "Run `python -m scripts.generate_persona_cards`."
            )
        return output_path

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")
    return output_path


def main() -> int:
    """CLI entry point."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Check that generated artifact is up to date without writing changes.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="Target output path (default: _includes/generated/persona-cards.qmd)",
    )
    parser.add_argument(
        "--base-dir",
        default="resources",
        help="Base directory from which relative links are computed (default: resources)",
    )
    args = parser.parse_args()

    try:
        out = generate_persona_cards(
            check=args.check, output_path=args.output, base_dir=args.base_dir
        )
        if args.check:
            logger.info("Persona cards include is up to date: %s", out)
        else:
            logger.info("Generated persona cards include: %s", out)
        return 0
    except Exception as exc:
        logger.error("Persona cards generation check failed: %s", exc)
        return 1


if __name__ == "__main__":
    sys.exit(main())
