#!/usr/bin/env python3
"""Post-render processor for citation metadata and downloads (WEB-07.2 #4544).

Post-processes HTML files generated by Quarto:
1. Strips invalid NaN date metadata tags (`NaN-NaN-NaN`, `NaN`) emitted by
   Quarto on unverified pages, ensuring `citation_publication_date` is only
   present for owner-verified publication dates.
2. Extracts BibTeX citations from rendered `<section id="quarto-citation">`
   blocks and saves them as standalone `.bib` files alongside the HTML.
3. Injects accessible BibTeX download links into the citation section.
4. Ensures the `#citation` anchor resolves directly to the citation section.
"""

from __future__ import annotations

import argparse
import html
import logging
import os
import re
import sys
from pathlib import Path

logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
logger = logging.getLogger(__name__)

NAN_META_PATTERN = re.compile(
    r'\s*<meta\s+name="citation_(?:publication_date|cover_date|year|online_date)"\s+content="NaN(?:-NaN-NaN)?"\s*/?>\n?',
    re.IGNORECASE,
)

BIBTEX_CODE_PATTERN = re.compile(
    r'<pre\s+class="[^"]*quarto-appendix-bibtex[^"]*"><code\s+class="[^"]*bibtex[^"]*">(.*?)</code>',
    re.DOTALL | re.IGNORECASE,
)

CITATION_SECTION_PATTERN = re.compile(
    r'(<section\s+class="[^"]*quarto-appendix-contents[^"]*"\s+id="quarto-citation">)',
    re.IGNORECASE,
)

BIBTEX_LABEL_PATTERN = re.compile(
    r'(<div\s+class="quarto-appendix-secondary-label">Bib(?:La)?TeX citation:</div>)',
    re.IGNORECASE,
)


TITLE_BLOCK_PATTERN = re.compile(
    r'(<header\b[^>]*\bid="title-block-header"[^>]*>)(.*?)(</header>)',
    re.DOTALL | re.IGNORECASE,
)
INVALID_TITLE_DATE_PATTERN = re.compile(
    r'(<p\s+class="date"\s*>)\s*Invalid Date\s*(</p>)',
    re.IGNORECASE,
)


def normalize_title_publication_date(content: str) -> str:
    """Replace Quarto's invalid title-date placeholder without altering article prose."""

    def replace_title(match: re.Match[str]) -> str:
        title = INVALID_TITLE_DATE_PATTERN.sub(r"\1Date unverified\2", match.group(2))
        return match.group(1) + title + match.group(3)

    return TITLE_BLOCK_PATTERN.sub(replace_title, content)


def process_html_content(content: str, html_path: Path) -> tuple[str, str | None]:
    """Process one rendered HTML document's citation metadata and extract BibTeX.

    Parameters
    ----------
    content : str
        The raw HTML document content.
    html_path : Path
        Path to the HTML file (used for relative links and naming).

    Returns
    -------
    tuple[str, str | None]
        The updated HTML content and the extracted BibTeX string (if any).
    """
    # 1. Strip NaN citation date meta tags emitted by Quarto for unverified dates
    if NAN_META_PATTERN.search(content):
        content = NAN_META_PATTERN.sub("", content)

    # 2. Extract BibTeX code if present
    bibtex_match = BIBTEX_CODE_PATTERN.search(content)
    bibtex_str: str | None = None
    if bibtex_match:
        raw_code = bibtex_match.group(1)
        bibtex_str = html.unescape(raw_code).strip() + "\n"

        # 3. Add #citation anchor target if not already present
        if 'id="citation"' not in content:
            content = CITATION_SECTION_PATTERN.sub(
                r'\1<a id="citation" class="visually-hidden" aria-hidden="true"></a>',
                content,
                count=1,
            )

        # 4. Inject download link next to BibTeX label if not present
        download_marker = "quarto-citation-bibtex-download"
        if download_marker not in content:
            bib_filename = f"{html_path.stem}.bib"
            download_html = (
                f'<div class="quarto-appendix-secondary-label">'
                f"BibTeX citation: "
                f'<a href="{bib_filename}" download="{bib_filename}" '
                f'class="btn btn-sm btn-outline-secondary {download_marker}" '
                f'style="margin-left: 0.5rem; text-decoration: none; font-size: 0.75rem; color: var(--text-primary); border-color: var(--color-neutral-400);" '
                f'role="button">Download .bib</a>'
                f"</div>"
            )
            content = BIBTEX_LABEL_PATTERN.sub(download_html, content, count=1)

    # 5. Fix WCAG / axe-core aria-required-parent violation (WEB-09.1 #4561):
    # Quarto emits <div id="ref-..." class="csl-entry quarto-appendix-citeas" role="listitem">
    # without an enclosing element bearing role="list". Strip role="listitem" so the single
    # standalone citation is a standard content container without an unsatisfied ARIA parent requirement.
    if "quarto-appendix-citeas" in content and 'role="listitem"' in content:

        def _strip_citeas_listitem(m: re.Match[str]) -> str:
            tag = m.group(0)
            return re.sub(r'\s+role="listitem"', "", tag, flags=re.IGNORECASE)

        content = re.sub(
            r'<div\s+[^>]*class="[^"]*quarto-appendix-citeas[^"]*"[^>]*>',
            _strip_citeas_listitem,
            content,
            count=1,
            flags=re.IGNORECASE,
        )

    return normalize_title_publication_date(content), bibtex_str


def process_directory(docs_dir: Path) -> int:
    """Process all rendered HTML files in the output directory.

    Parameters
    ----------
    docs_dir : Path
        The directory containing rendered HTML output (e.g. docs/).

    Returns
    -------
    int
        Count of processed HTML files.
    """
    if not docs_dir.is_dir():
        logger.warning("Docs directory does not exist: %s", docs_dir)
        return 0

    count = 0
    for html_file in docs_dir.rglob("*.html"):
        try:
            content = html_file.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            try:
                content = html_file.read_text(encoding="utf-8-sig")
            except Exception as exc:
                logger.warning("Skipping unreadable file %s: %s", html_file, exc)
                continue

        updated_content, bibtex_str = process_html_content(content, html_file)

        if bibtex_str:
            bib_file = html_file.with_suffix(".bib")
            bib_file.write_text(bibtex_str, encoding="utf-8")

        if updated_content != content:
            html_file.write_text(updated_content, encoding="utf-8")
            count += 1

    logger.info("Processed citation metadata on %d HTML file(s) in %s", count, docs_dir)
    return count


def main() -> int:
    """CLI entry point for Quarto post-render and standalone checks."""
    parser = argparse.ArgumentParser(
        description="Clean citation metadata and generate BibTeX downloads."
    )
    parser.add_argument(
        "--docs-dir",
        type=Path,
        default=None,
        help="Path to output directory (defaults to QUARTO_PROJECT_OUTPUT_DIR or docs)",
    )
    args = parser.parse_args()

    output_dir = args.docs_dir
    if output_dir is None:
        env_dir = os.environ.get("QUARTO_PROJECT_OUTPUT_DIR")
        if env_dir:
            output_dir = Path(env_dir)
        else:
            repo_root = Path(__file__).resolve().parent.parent
            output_dir = repo_root / "docs"

    process_directory(output_dir)
    return 0


if __name__ == "__main__":
    sys.exit(main())
