"""Deterministic generator for governed research release registries and Quarto partials."""

from __future__ import annotations

import json
import logging
from pathlib import Path

import jsonschema  # type: ignore[import-untyped]

from src.affine_control.research_releases.vocabulary import (
    RELEASE_AUTHORITY_BOUNDARY,
    ResearchReleasePackage,
)

logger = logging.getLogger(__name__)


def build_authoritative_releases(repo_root: Path) -> list[ResearchReleasePackage]:
    """Build authoritative list of governed research release packages."""
    # Issue #4749: the former atlas entry supplied unsupported execution/reviewer
    # metadata and rehashed current bytes under a fixed historical pin.
    # A file's existence is not a release attestation. Keep this registry empty
    # until an explicit, revision-bound execution and review record is adopted.
    return []


def render_releases_summary(releases: list[ResearchReleasePackage]) -> str:
    """Render accessible Quarto summary partial for research releases."""
    lines = [
        "<!-- Generated by scripts/generate_research_releases.py. DO NOT EDIT. -->",
        "",
        '::: {.callout-note appearance="simple" role="region" aria-label="Research Releases"}',
        "## Governed Research Artifact Releases",
        "",
        "| Release ID | Maturity | Protocol Scope | Pinned Commit | Verification |",
        "|---|---|---|---|---|",
    ]

    if not releases:
        return (
            "\n".join(lines[:5])
            + "\nNo verified research release is registered. The atlas remains a reading aid; "
            "its file and synthetic checks do not establish measured results, independent "
            "review, or a qualified workflow.\n\n" + f"*{RELEASE_AUTHORITY_BOUNDARY}*\n:::\n"
        )

    for rel in releases:
        rev = rel.independent_review
        lines.append(
            f"| `{rel.release_id}` | **{rel.release_level}** | `{rel.protocol_id}` | "
            f"`{rel.git_commit[:8]}` | {rev.disposition.capitalize()} by `{rev.reviewer_id}` |"
        )

    lines.extend(
        [
            "",
            "### Artifact Manifest & Epistemological Boundaries",
            "",
        ]
    )

    for rel in releases:
        lines.append(f"#### {rel.title} (`{rel.release_id}`)")
        lines.append(f"- **Maturity**: `{rel.release_level}`")
        lines.append(f"- **Pinned Source**: [`{rel.git_commit[:10]}`]({rel.repository_url})")
        lines.append(f"- **Artifacts** ({len(rel.artifacts)} file(s)):")
        for art in rel.artifacts:
            short_hash = f"{art.sha256[:16]}..."
            lines.append(
                f"  - `{art.path}` (`{short_hash}`, {art.byte_size:,} bytes) - {art.description}"
            )
        lim = rel.uncertainty_and_limitations
        lines.append("- **Modeled vs Measured Separation**:")
        lines.append(f"  - *Modeled*: {', '.join(lim.modeled_quantities)}")
        lines.append(f"  - *Assumed*: {', '.join(lim.assumed_quantities)}")
        lines.append(f"  - *Unavailable*: {', '.join(lim.unavailable_quantities)}")
        commit_short = rel.independent_review.verification_commit[:8]
        lines.append(
            f"- **Independent Review**: {rel.independent_review.disposition} "
            f"(*Commit: `{commit_short}`*)"
        )
        lines.append("")

    lines.extend(
        [
            f"*{RELEASE_AUTHORITY_BOUNDARY}*",
            ":::",
        ]
    )

    return "\n".join(lines) + "\n"


def generate_research_releases(
    *,
    check: bool = False,
    repo_root: Path | None = None,
) -> tuple[Path, Path]:
    """Generate or verify research release artifacts."""
    root = repo_root or Path(__file__).resolve().parent.parent.parent.parent
    registry_path = root / "data/trust/generated/research_releases_registry.json"
    partial_path = root / "_includes/generated/research-releases-summary.qmd"

    releases = build_authoritative_releases(root)
    schema_path = root / "schemas/research-artifact-release-v1.schema.json"

    # Validate each release with schema
    if schema_path.is_file():
        schema = json.loads(schema_path.read_text(encoding="utf-8"))
        for rel in releases:
            jsonschema.validate(instance=rel.to_dict(), schema=schema)

    registry_dict = {
        "authority_boundary": RELEASE_AUTHORITY_BOUNDARY,
        "releases": [r.to_dict() for r in releases],
        "schema_version": "affinedrift.research-artifact-release-registry/v1",
        "total_releases": len(releases),
    }

    registry_content = json.dumps(registry_dict, indent=2, ensure_ascii=False) + "\n"
    partial_content = render_releases_summary(releases)

    if check:
        if not registry_path.is_file():
            raise FileNotFoundError(f"Missing release registry: {registry_path}")
        if json.loads(registry_path.read_text(encoding="utf-8")) != registry_dict:
            raise ValueError(f"Release registry is stale: {registry_path}")
        if not partial_path.is_file():
            raise FileNotFoundError(f"Missing release partial: {partial_path}")
        if partial_path.read_text(encoding="utf-8") != partial_content:
            raise ValueError(f"Release partial is stale: {partial_path}")
        return registry_path, partial_path

    registry_path.parent.mkdir(parents=True, exist_ok=True)
    registry_path.write_text(registry_content, encoding="utf-8")

    partial_path.parent.mkdir(parents=True, exist_ok=True)
    partial_path.write_text(partial_content, encoding="utf-8")

    logger.info(
        "Successfully generated research release artifacts at %s and %s",
        registry_path,
        partial_path,
    )
    return registry_path, partial_path
