"""Utilities for managing GitHub issues.

This module provides helpers for generating issue content, titles,
and interacting with the GitHub CLI.
"""

from __future__ import annotations

from pathlib import Path


def get_repo_short_name(repo_path: Path | None = None) -> str:
    """Get a standardized short name for the repository.

    Args:
        repo_path: Path to the repository root.

    Returns:
        Standardized short name string.
    """
    if repo_path is None:
        repo_path = Path.cwd()

    repo_name = repo_path.name
    repo_short_names = {
        "Gasification_Model": "GasModel",
        "Tools": "Tools",
        "AffineDrift": "AffineDrift",
        "Games": "Games",
        "Golf_Modeling_Suite": "GolfSuite",
        "MLProjects": "MLProj",
        "Playground": "Playground",
        "MEB_Conversion": "MEBConv",
        "Repository_Management": "RepoMgmt",
    }
    return repo_short_names.get(repo_name, repo_name[:8])


def format_issue_body(
    severity: str,
    category: str,
    source: str,
    description: str,
    timestamp: str = "Unknown",
) -> str:
    """Format the body of a GitHub issue from assessment results.

    Args:
        severity: Severity level (e.g., CRITICAL).
        category: Assessment category.
        source: Source of the finding.
        description: Detailed description of the problem.
        timestamp: When the assessment was run.

    Returns:
        Formatted Markdown string for the issue body.
    """
    return f"""## Issue Description

**Severity**: {severity}
**Category**: {category}
**Source**: {source}
**Identified**: {timestamp}

### Problem

{description}


### Impact

This issue was identified during automated repository assessment and requires attention.

### References

- Assessment Report: {source}
- Full Assessment: docs/assessments/Comprehensive_Assessment.md

### Next Steps

1. Investigate the issue
2. Determine root cause
3. Implement fix
4. Verify resolution
5. Update tests if needed

---

🤖 Auto-generated by Jules Assessment Auto-Fix
"""
