"""Utilities for managing GitHub issues.

This module provides helpers for generating issue content, titles,
and interacting with the GitHub CLI.
"""

from __future__ import annotations

import logging
from pathlib import Path

from src.core.contracts import require

logger = logging.getLogger(__name__)


def get_repo_short_name(repo_path: Path | None = None) -> str:
    """Get a standardized short name for the repository.

    Args:
        repo_path: Path to the repository root.

    Returns:
        Standardized short name string.
    """
    if repo_path is None:
        repo_path = Path.cwd()

    repo_name = repo_path.name
    repo_short_names = {
        "Gasification_Model": "GasModel",
        "Tools": "Tools",
        "AffineDrift": "AffineDrift",
        "Games": "Games",
        "Golf_Modeling_Suite": "GolfSuite",
        "MLProjects": "MLProj",
        "Playground": "Playground",
        "MEB_Conversion": "MEBConv",
        "Repository_Management": "RepoMgmt",
    }
    return repo_short_names.get(repo_name, repo_name[:8])


def _issue_body_template(
    severity: str,
    category: str,
    source: str,
    description: str,
    timestamp: str,
) -> str:
    """Return the formatted Markdown template for a GitHub issue body."""
    return (
        f"## Issue Description\n\n"
        f"**Severity**: {severity}\n"
        f"**Category**: {category}\n"
        f"**Source**: {source}\n"
        f"**Identified**: {timestamp}\n\n"
        f"### Problem\n\n{description}\n\n\n"
        f"### Impact\n\n"
        f"This issue was identified during automated repository assessment"
        f" and requires attention.\n\n"
        f"### References\n\n"
        f"- Assessment Report: {source}\n"
        f"- Full Assessment: docs/assessments/Comprehensive_Assessment.md\n\n"
        f"### Next Steps\n\n"
        f"1. Investigate the issue\n"
        f"2. Determine root cause\n"
        f"3. Implement fix\n"
        f"4. Verify resolution\n"
        f"5. Update tests if needed\n\n"
        f"---\n\n"
        f"🤖 Auto-generated by Jules Assessment Auto-Fix\n"
    )


def format_issue_body(
    severity: str,
    category: str,
    source: str,
    description: str,
    timestamp: str = "Unknown",
) -> str:
    """Format the body of a GitHub issue from assessment results.

    Args:
        severity: Severity level (e.g., CRITICAL).
        category: Assessment category.
        source: Source of the finding.
        description: Detailed description of the problem.
        timestamp: When the assessment was run.

    Returns:
        Formatted Markdown string for the issue body.
    """
    require(len(severity) > 0, "severity must not be empty")
    require(len(category) > 0, "category must not be empty")
    require(len(description) > 0, "description must not be empty")
    return _issue_body_template(severity, category, source, description, timestamp)
