project:
  type: book

book:
  title: "The Geometry of Motion"
  author: "D. Kraft"
  date: "2026-02-22"
  chapters:
    - index.qmd
    - volume0.qmd
    - volume1.qmd
    - volume2.qmd

bibliography: ../geometry_of_motion.bib

format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
  pdf:
    documentclass: book
    keep-tex: true
    number-sections: true
